set(_AMENT_PACKAGE_NAME "cti_chassis_handdle")
set(cti_chassis_handdle_VERSION "20.0.0")
set(cti_chassis_handdle_MAINTAINER "neousys <neousys@todo.todo>")
set(cti_chassis_handdle_BUILD_DEPENDS "rclcpp" "std_msgs" "tf2_ros" "tf2_geometry_msgs" "cti_msgs" "ctilog" "nav_msgs" "sensor_msgs" "cti_chassis_msgs")
set(cti_chassis_handdle_BUILDTOOL_DEPENDS "ament_cmake")
set(cti_chassis_handdle_BUILD_EXPORT_DEPENDS "rclcpp" "std_msgs" "tf2_ros" "tf2_geometry_msgs" "cti_msgs" "ctilog" "nav_msgs" "sensor_msgs" "cti_chassis_msgs")
set(cti_chassis_handdle_BUILDTOOL_EXPORT_DEPENDS )
set(cti_chassis_handdle_EXEC_DEPENDS "rclcpp" "std_msgs" "tf2_ros" "tf2_geometry_msgs" "cti_msgs" "ctilog" "nav_msgs" "sensor_msgs" "cti_chassis_msgs")
set(cti_chassis_handdle_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(cti_chassis_handdle_GROUP_DEPENDS )
set(cti_chassis_handdle_MEMBER_OF_GROUPS )
set(cti_chassis_handdle_DEPRECATED "")
set(cti_chassis_handdle_EXPORT_TAGS)
list(APPEND cti_chassis_handdle_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
